---
- name: Install unzip
  apt: 
    name: unzip
    update_cache: yes

- name: Create directory for LanguageTool
  file:
    path: /opt/languagetool
    state: directory
    mode: 0755

- name: Download and unzip LanguageTool 4.0
  unarchive:
    src: https://www.languagetool.org/download/LanguageTool-4.0.zip
    dest: /opt/languagetool
    remote_src: yes

- name: Configure LanguageTool server.properties
  template:
    src: server.properties.j2
    dest: /opt/languagetool/server.properties
    owner: ubuntu
    group: ubuntu
    mode: 0644

- name: Add LanguageTool systemd service configuration
  become: true
  template:
    src: languagetool.service.j2
    dest: /etc/systemd/system/languagetool.service
    owner: root
    group: root
    mode: 0644

- name: Make sure the LanguageTool service is enabled on boot and start/restart it
  systemd: 
    name: languagetool
    enabled: yes
    state: restarted 
    daemon_reload: yes
